"""
Authoritative Static Capability Catalog for Animus Smart Room.
Defines the complete verified baseline of all smart room physical capabilities
with rigorous parameter limits, operation types, safety levels, and hardware constraints.
"""

from typing import List
from capability_registry.models import (
    Subsystem,
    OperationType,
    SafetyLevel,
    CapabilityStatus,
    ParameterType,
    ParameterConstraint,
    CapabilityDefinition
)

AUTHORITATIVE_CAPABILITIES: List[CapabilityDefinition] = [
    # =========================================================================
    # 1. PROJECTOR SUBSYSTEM (Zebronics PixaPlay 25 / ProjectorController)
    # =========================================================================
    CapabilityDefinition(
        canonical_id="PROJECTOR_POWER_WAKE",
        subsystem=Subsystem.PROJECTOR,
        description="Wakes projector display from standby mode over ADB Wi-Fi via KEYCODE_WAKEUP.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_wake",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        preconditions=["projector.reachable == True"],
        expected_state_transition={"projector.power": True}
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_POWER_SLEEP",
        subsystem=Subsystem.PROJECTOR,
        description="Puts projector display into standby mode over ADB Wi-Fi via KEYCODE_SLEEP.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_sleep",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        preconditions=["projector.power == True"],
        expected_state_transition={"projector.power": False}
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_POWER_OFF_OEM",
        subsystem=Subsystem.PROJECTOR,
        description="Initiates graceful optical-engine shutdown via OEM PowerActivity with 3-second cooling sequence.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_power_off_oem",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.MEDIUM_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"projector.power": False}
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_POWER_ON_COLD",
        subsystem=Subsystem.PROJECTOR,
        description="Cold power-on when projector is completely unpowered (unavailable via ADB; pending IR blaster hardware).",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_power_on_cold",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=False,
        readback_verification_expected=False,
        safety_level=SafetyLevel.RESTRICTED,
        status=CapabilityStatus.UNSUPPORTED_HARDWARE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_GET_POWER_STATE",
        subsystem=Subsystem.PROJECTOR,
        description="Reads physical wakefulness, display power, and interactivity state via dumpsys.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_get_power_state",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_SWITCH_HDMI1",
        subsystem=Subsystem.PROJECTOR,
        description="Switches physical projector display input source to HDMI 1 (Fire TV input).",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_switch_hdmi1",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        preconditions=["projector.power == True"],
        expected_state_transition={"projector.input_source": "HDMI_1"}
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_SWITCH_ANDROID_HOME",
        subsystem=Subsystem.PROJECTOR,
        description="Switches physical projector input source to internal Android TV home launcher.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_switch_android_home",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        preconditions=["projector.power == True"],
        expected_state_transition={"projector.input_source": "ANDROID_HOME"}
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_SWITCH_USB_FILEMGR",
        subsystem=Subsystem.PROJECTOR,
        description="Launches USB File Manager / Media Player on projector.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_switch_usb_filemgr",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"projector.input_source": "USB"}
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_GET_SOURCE",
        subsystem=Subsystem.PROJECTOR,
        description="Reads current active input source on physical projector.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_get_source",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_GET_SIGNAL_STATE",
        subsystem=Subsystem.PROJECTOR,
        description="Queries dumpsys tv_input under HDMI0000C2 to verify active streaming video handshake.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_get_signal_state",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_GET_BRIGHTNESS",
        subsystem=Subsystem.PROJECTOR,
        description="Reads normalized projector screen brightness (0 to 100%).",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_get_brightness",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_GET_CONTENT_TITLE",
        subsystem=Subsystem.PROJECTOR,
        description="Reads active projected media/content title via Android media session or HDMI pass-through.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_get_content_title",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_SET_BRIGHTNESS",
        subsystem=Subsystem.PROJECTOR,
        description="Adjusts physical projector display brightness scalar between 1 and 100% with read-back verification.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_set_brightness",
        operation_type=OperationType.ACTION,
        parameters={
            "brightness": ParameterConstraint(
                name="brightness",
                param_type=ParameterType.INTEGER,
                required=True,
                min_value=1,
                max_value=100,
                description="Target brightness level (1 to 100)"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        preconditions=["projector.power == True"]
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_SET_CONTRAST",
        subsystem=Subsystem.PROJECTOR,
        description="Sets physical projector display contrast scalar (deferred pending controller contrast API).",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_set_contrast",
        operation_type=OperationType.ACTION,
        parameters={
            "contrast": ParameterConstraint(
                name="contrast",
                param_type=ParameterType.INTEGER,
                required=True,
                min_value=1,
                max_value=100,
                description="Target contrast level (1 to 100)"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.DEFERRED_PENDING_IMPLEMENTATION
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_GET_HARDWARE_HEALTH",
        subsystem=Subsystem.PROJECTOR,
        description="Reads live optical LED light temperature and dual cooling fan RPMs via getprop telemetry.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_get_hardware_health",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_AUTO_FOCUS",
        subsystem=Subsystem.PROJECTOR,
        description="Triggers electric motor camera-assisted auto-focus sequence via OEM intent.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_auto_focus",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_AUTO_KEYSTONE",
        subsystem=Subsystem.PROJECTOR,
        description="Triggers gyro-assisted auto-keystone correction via OEM intent.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_auto_keystone",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_NAV_HOME",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_HOME (3) to projector.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_nav_home",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_NAV_BACK",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_BACK (4) to projector.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_nav_back",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_NAV_MENU",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_MENU (82) to projector.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_nav_menu",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_NAV_DPAD_UP",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_DPAD_UP (19) to projector.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_nav_dpad_up",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_NAV_DPAD_DOWN",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_DPAD_DOWN (20) to projector.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_nav_dpad_down",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_NAV_DPAD_LEFT",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_DPAD_LEFT (21) to projector.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_nav_dpad_left",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_NAV_DPAD_RIGHT",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_DPAD_RIGHT (22) to projector.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_nav_dpad_right",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_NAV_SELECT",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_DPAD_CENTER (23) to projector.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_nav_select",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_VOLUME_UP",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_VOLUME_UP (24) to projector internal speaker.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_volume_up",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_VOLUME_DOWN",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_VOLUME_DOWN (25) to projector internal speaker.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_volume_down",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_VOLUME_MUTE",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_VOLUME_MUTE (164) to projector internal speaker.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_volume_mute",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_MEDIA_PLAY_PAUSE",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_MEDIA_PLAY_PAUSE (85) to projector internal media player.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_media_play_pause",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_MEDIA_NEXT",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_MEDIA_NEXT (87) to projector internal media player.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_media_next",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_MEDIA_PREVIOUS",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_MEDIA_PREVIOUS (88) to projector internal media player.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_media_previous",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_MEDIA_STOP",
        subsystem=Subsystem.PROJECTOR,
        description="Sends KEYCODE_MEDIA_STOP (86) to projector internal media player.",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_media_stop",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_SWITCH_HDMI2",
        subsystem=Subsystem.PROJECTOR,
        description="HDMI 2 port input switch (rejected: projector hardware only has 1 physical HDMI port).",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_switch_hdmi2",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=False,
        readback_verification_expected=False,
        safety_level=SafetyLevel.RESTRICTED,
        status=CapabilityStatus.UNSUPPORTED_HARDWARE
    ),
    CapabilityDefinition(
        canonical_id="PROJECTOR_SWITCH_HDMI3",
        subsystem=Subsystem.PROJECTOR,
        description="HDMI 3 port input switch (rejected: projector hardware only has 1 physical HDMI port).",
        underlying_controller="ProjectorController",
        underlying_capability_name="projector_switch_hdmi3",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=False,
        readback_verification_expected=False,
        safety_level=SafetyLevel.RESTRICTED,
        status=CapabilityStatus.UNSUPPORTED_HARDWARE
    ),

    # =========================================================================
    # 2. AIR CONDITIONER SUBSYSTEM (Tuya Split Inverter AC / AcController)
    # =========================================================================
    CapabilityDefinition(
        canonical_id="AC_GET_STATUS",
        subsystem=Subsystem.AC,
        description="Reads live Tuya DPs (power, temperature, mode, fan speed, ambient temperature).",
        underlying_controller="AcController",
        underlying_capability_name="ac_get_status",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="AC_POWER_ON",
        subsystem=Subsystem.AC,
        description="Powers ON the air conditioner compressor and fan via Tuya DP 1.",
        underlying_controller="AcController",
        underlying_capability_name="ac_power_on",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"ac.power": True}
    ),
    CapabilityDefinition(
        canonical_id="AC_POWER_OFF",
        subsystem=Subsystem.AC,
        description="Powers OFF the air conditioner unit via Tuya DP 1.",
        underlying_controller="AcController",
        underlying_capability_name="ac_power_off",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"ac.power": False}
    ),
    CapabilityDefinition(
        canonical_id="AC_SET_TEMPERATURE",
        subsystem=Subsystem.AC,
        description="Sets target thermostat cooling temperature between 16 and 30 degrees Celsius via Tuya DP 2.",
        underlying_controller="AcController",
        underlying_capability_name="ac_set_temperature",
        operation_type=OperationType.ACTION,
        parameters={
            "temperature": ParameterConstraint(
                name="temperature",
                param_type=ParameterType.INTEGER,
                required=True,
                min_value=16,
                max_value=30,
                description="Target temperature in Celsius (16 to 30)"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        preconditions=["ac.power == True"]
    ),
    CapabilityDefinition(
        canonical_id="AC_SET_MODE",
        subsystem=Subsystem.AC,
        description="Sets AC operating mode (COOL, AUTO, DRY, FAN) via Tuya DP 4. HEAT is unsupported on cooling-only hardware.",
        underlying_controller="AcController",
        underlying_capability_name="ac_set_mode",
        operation_type=OperationType.ACTION,
        parameters={
            "mode": ParameterConstraint(
                name="mode",
                param_type=ParameterType.ENUM,
                required=True,
                allowed_values=["COOL", "AUTO", "DRY", "FAN"],
                description="Operating mode"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        preconditions=["ac.power == True"]
    ),
    CapabilityDefinition(
        canonical_id="AC_SET_FAN",
        subsystem=Subsystem.AC,
        description="Sets AC blower fan speed (LOW, MEDIUM, HIGH, AUTO) via Tuya DP 5.",
        underlying_controller="AcController",
        underlying_capability_name="ac_set_fan",
        operation_type=OperationType.ACTION,
        parameters={
            "speed": ParameterConstraint(
                name="speed",
                param_type=ParameterType.ENUM,
                required=True,
                allowed_values=["LOW", "MEDIUM", "HIGH", "AUTO"],
                description="Blower fan speed"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        preconditions=["ac.power == True"]
    ),
    CapabilityDefinition(
        canonical_id="AC_SET_HEAT",
        subsystem=Subsystem.AC,
        description="Heat mode (unsupported on cooling-only physical hardware).",
        underlying_controller="AcController",
        underlying_capability_name="ac_set_heat",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.RESTRICTED,
        status=CapabilityStatus.UNSUPPORTED_HARDWARE
    ),
    CapabilityDefinition(
        canonical_id="AC_SET_SWING",
        subsystem=Subsystem.AC,
        description="Louvre swing oscillation (unsupported over Wi-Fi on physical hardware).",
        underlying_controller="AcController",
        underlying_capability_name="ac_set_swing",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.RESTRICTED,
        status=CapabilityStatus.UNSUPPORTED_HARDWARE
    ),

    # =========================================================================
    # 3. FIRE TV SUBSYSTEM (Amazon Fire TV Stick Lite / FireTVCapabilityRegistry)
    # =========================================================================
    CapabilityDefinition(
        canonical_id="FIRE_TV_CONNECTIVITY_CHECK",
        subsystem=Subsystem.FIRE_TV,
        description="Checks TCP socket connectivity to Fire TV over ADB port 5555.",
        underlying_controller="FireTvController",
        underlying_capability_name="connectivity_check",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=False,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_POWER_WAKE",
        subsystem=Subsystem.FIRE_TV,
        description="Wakes Fire TV from sleep/screensaver over ADB.",
        underlying_controller="FireTvController",
        underlying_capability_name="power_wake",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"fire_tv.power_state": "AWAKE"}
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_POWER_SLEEP",
        subsystem=Subsystem.FIRE_TV,
        description="Puts Fire TV to sleep over ADB.",
        underlying_controller="FireTvController",
        underlying_capability_name="power_sleep",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"fire_tv.power_state": "ASLEEP"}
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_POWER_GET_STATE",
        subsystem=Subsystem.FIRE_TV,
        description="Reads physical wakefulness state of Fire TV via dumpsys power.",
        underlying_controller="FireTvController",
        underlying_capability_name="power_get_state",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_NAV_HOME",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_HOME to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="navigation_home",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_NAV_BACK",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_BACK to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="navigation_back",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_NAV_SELECT",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_DPAD_CENTER to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="navigation_select",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_NAV_DPAD",
        subsystem=Subsystem.FIRE_TV,
        description="Sends directional DPAD navigation keys to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="navigation_dpad",
        operation_type=OperationType.ACTION,
        parameters={
            "direction": ParameterConstraint(
                name="direction",
                param_type=ParameterType.ENUM,
                required=True,
                allowed_values=["UP", "DOWN", "LEFT", "RIGHT"],
                description="DPAD navigation direction"
            )
        },
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_APP_LAUNCH_YOUTUBE",
        subsystem=Subsystem.FIRE_TV,
        description="Launches YouTube TV application directly on Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="app_launch_youtube",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"fire_tv.foreground_app": "com.google.android.youtube.tv"}
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_APP_GET_FOREGROUND",
        subsystem=Subsystem.FIRE_TV,
        description="Reads focused foreground package name from dumpsys window.",
        underlying_controller="FireTvController",
        underlying_capability_name="app_get_foreground",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_GET_CONTENT_TITLE",
        subsystem=Subsystem.FIRE_TV,
        description="Reads active media/content title playing on Fire TV via dumpsys media_session or foreground app.",
        underlying_controller="FireTvController",
        underlying_capability_name="get_content_title",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MEDIA_DIRECT_YOUTUBE",
        subsystem=Subsystem.FIRE_TV,
        description="Launches YouTube video directly via Android Intent.",
        underlying_controller="FireTvController",
        underlying_capability_name="media_direct_youtube",
        operation_type=OperationType.ACTION,
        parameters={
            "video_id": ParameterConstraint(
                name="video_id",
                param_type=ParameterType.STRING,
                required=True,
                description="YouTube 11-character video ID"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MEDIA_DIRECT_PROVIDER",
        subsystem=Subsystem.FIRE_TV,
        description="Launches media directly on target streaming provider (Netflix, Prime, Hotstar, JioCinema, SonyLIV, Zee5).",
        underlying_controller="FireTvController",
        underlying_capability_name="media_direct_provider",
        operation_type=OperationType.ACTION,
        parameters={
            "provider": ParameterConstraint(
                name="provider",
                param_type=ParameterType.STRING,
                required=True,
                allowed_values=["youtube", "netflix", "prime", "hotstar", "jiocinema", "sonyliv", "zee5"],
                description="Streaming provider identifier"
            ),
            "content": ParameterConstraint(
                name="content",
                param_type=ParameterType.STRING,
                required=False,
                description="Content title, query, or URI"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MEDIA_SEARCH_YOUTUBE",
        subsystem=Subsystem.FIRE_TV,
        description="Searches YouTube on Fire TV via deep link intent.",
        underlying_controller="FireTvController",
        underlying_capability_name="media_search_youtube",
        operation_type=OperationType.ACTION,
        parameters={
            "query": ParameterConstraint(
                name="query",
                param_type=ParameterType.STRING,
                required=True,
                description="Search query string"
            )
        },
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MEDIA_VERIFY_YOUTUBE",
        subsystem=Subsystem.FIRE_TV,
        description="Verifies that YouTube is running in the foreground.",
        underlying_controller="FireTvController",
        underlying_capability_name="media_verify_youtube",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MEDIA_PLAY",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_MEDIA_PLAY to Fire TV active media session.",
        underlying_controller="FireTvController",
        underlying_capability_name="media_play",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MEDIA_PAUSE",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_MEDIA_PAUSE to Fire TV active media session.",
        underlying_controller="FireTvController",
        underlying_capability_name="media_pause",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MEDIA_TOGGLE",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_MEDIA_PLAY_PAUSE to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="media_toggle",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MEDIA_STOP",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_MEDIA_STOP to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="media_stop",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MEDIA_NEXT",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_MEDIA_NEXT to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="media_next",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MEDIA_PREVIOUS",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_MEDIA_PREVIOUS to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="media_previous",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_VOLUME_UP",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_VOLUME_UP to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="volume_up",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_VOLUME_DOWN",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_VOLUME_DOWN to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="volume_down",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_MUTE",
        subsystem=Subsystem.FIRE_TV,
        description="Sends KEYCODE_VOLUME_MUTE to Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="mute",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_BT_GET_STATUS",
        subsystem=Subsystem.FIRE_TV,
        description="Reads Bluetooth adapter and bonded device connection status on Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="bt_get_status",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_BT_CONNECT_SOUNDBAR",
        subsystem=Subsystem.FIRE_TV,
        description="Connects LG SNC4R Soundbar to Fire TV with direct-to-fallback escalation.",
        underlying_controller="FireTvController",
        underlying_capability_name="bt_connect_soundbar",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"fire_tv.soundbar_connected": True}
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_BT_CONNECT_SOUNDBAR_DIRECT",
        subsystem=Subsystem.FIRE_TV,
        description="Connects LG SNC4R Soundbar directly via input tap on paired settings UI coordinate.",
        underlying_controller="FireTvController",
        underlying_capability_name="bt_connect_soundbar_direct",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"fire_tv.soundbar_connected": True}
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_BT_CONNECT_SOUNDBAR_FALLBACK",
        subsystem=Subsystem.FIRE_TV,
        description="Connects LG SNC4R Soundbar using fallback intent navigation when direct tap fails.",
        underlying_controller="FireTvController",
        underlying_capability_name="bt_connect_soundbar_fallback",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"fire_tv.soundbar_connected": True}
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_BT_DISCONNECT_SOUNDBAR_DIRECT",
        subsystem=Subsystem.FIRE_TV,
        description="Disconnects LG SNC4R Soundbar from Fire TV.",
        underlying_controller="FireTvController",
        underlying_capability_name="bt_disconnect_soundbar_direct",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"fire_tv.soundbar_connected": False}
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_BT_IS_SOUNDBAR_CONNECTED",
        subsystem=Subsystem.FIRE_TV,
        description="Checks if LG SNC4R Soundbar is actively connected to Fire TV over Bluetooth.",
        underlying_controller="FireTvController",
        underlying_capability_name="bt_is_soundbar_connected",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_AUDIO_SWITCH_TO_FIRE_TV",
        subsystem=Subsystem.FIRE_TV,
        description="Transfers Soundbar audio sink ownership from PC to Fire TV.",
        underlying_controller="FireTvService",
        underlying_capability_name="audio_switch_to_fire_tv",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"soundbar.current_owner": "FIRE_TV", "soundbar.is_connected": True}
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_AUDIO_SWITCH_TO_PC",
        subsystem=Subsystem.FIRE_TV,
        description="Restores Soundbar audio sink ownership from Fire TV back to PC.",
        underlying_controller="FireTvService",
        underlying_capability_name="audio_switch_to_pc",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"soundbar.current_owner": "PC", "soundbar.is_connected": True}
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_PROJECTOR_SWITCH_HDMI1",
        subsystem=Subsystem.FIRE_TV,
        description="Switches physical Projector to HDMI 1 (Fire TV input) via integrated service.",
        underlying_controller="FireTvService",
        underlying_capability_name="projector_switch_hdmi1",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"projector.input_source": "HDMI_1"}
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_PROJECTOR_VERIFY_HDMI1",
        subsystem=Subsystem.FIRE_TV,
        description="Verifies that Projector is currently displaying HDMI 1.",
        underlying_controller="FireTvService",
        underlying_capability_name="projector_verify_hdmi1",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_AUTOMATION_MOVIE_MODE_START",
        subsystem=Subsystem.FIRE_TV,
        description="Orchestrates complete cinema workflow: wakes Fire TV, connects Soundbar, switches Projector to HDMI 1, launches content.",
        underlying_controller="FireTvService",
        underlying_capability_name="automation_movie_mode_start",
        operation_type=OperationType.AUTOMATION,
        parameters={
            "content": ParameterConstraint(name="content", param_type=ParameterType.STRING, required=False, description="Movie/show title or video ID"),
            "provider": ParameterConstraint(name="provider", param_type=ParameterType.STRING, required=False, description="Target streaming provider")
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.MEDIUM_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="FIRE_TV_AUTOMATION_MOVIE_MODE_STOP",
        subsystem=Subsystem.FIRE_TV,
        description="Stops cinema workflow: pauses media, transfers Soundbar to PC, optional projector shutdown.",
        underlying_controller="FireTvService",
        underlying_capability_name="automation_movie_mode_stop",
        operation_type=OperationType.AUTOMATION,
        parameters={
            "turn_off_projector": ParameterConstraint(name="turn_off_projector", param_type=ParameterType.BOOLEAN, required=False, default=False, description="Whether to put projector into standby")
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.MEDIUM_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),

    # =========================================================================
    # 4. PC HOST SUBSYSTEM (Windows Host / PcController / PcCommandRouter)
    # =========================================================================
    CapabilityDefinition(
        canonical_id="PC_GET_STATUS",
        subsystem=Subsystem.PC,
        description="Reads comprehensive authoritative status across Audio, Bluetooth, Media, and System.",
        underlying_controller="PcController",
        underlying_capability_name="pc_get_status",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_GET_AUDIO_STATUS",
        subsystem=Subsystem.PC,
        description="Reads current Windows CoreAudio master volume, mute state, default render endpoint, and active devices.",
        underlying_controller="PcController",
        underlying_capability_name="pc_get_audio_status",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_GET_VOLUME",
        subsystem=Subsystem.PC,
        description="Reads current master system volume percentage (0 to 100).",
        underlying_controller="PcController",
        underlying_capability_name="pc_get_volume",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_SET_VOLUME",
        subsystem=Subsystem.PC,
        description="Sets master audio volume on Windows host between 0 and 100 via in-process CoreAudio COM.",
        underlying_controller="PcController",
        underlying_capability_name="pc_set_volume",
        operation_type=OperationType.ACTION,
        parameters={
            "volume": ParameterConstraint(
                name="volume",
                param_type=ParameterType.INTEGER,
                required=True,
                min_value=0,
                max_value=100,
                description="Master volume level (0 to 100)"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_MUTE",
        subsystem=Subsystem.PC,
        description="Mutes Windows master audio endpoint via CoreAudio COM.",
        underlying_controller="PcController",
        underlying_capability_name="pc_mute",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"pc.is_muted": True}
    ),
    CapabilityDefinition(
        canonical_id="PC_UNMUTE",
        subsystem=Subsystem.PC,
        description="Unmutes Windows master audio endpoint via CoreAudio COM.",
        underlying_controller="PcController",
        underlying_capability_name="pc_unmute",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"pc.is_muted": False}
    ),
    CapabilityDefinition(
        canonical_id="PC_GET_AUDIO_OUTPUT",
        subsystem=Subsystem.PC,
        description="Enumerates active Windows CoreAudio playback render endpoints with device IDs and friendly names.",
        underlying_controller="PcController",
        underlying_capability_name="pc_get_audio_output",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_GET_BLUETOOTH_DEVICES",
        subsystem=Subsystem.PC,
        description="Enumerates local Bluetooth radio details and all paired/connected devices via 64-bit BluetoothApis.",
        underlying_controller="PcController",
        underlying_capability_name="pc_get_bluetooth_devices",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_MEDIA_PLAY_PAUSE",
        subsystem=Subsystem.PC,
        description="Sends VK_MEDIA_PLAY_PAUSE virtual keybd_event to active Windows media application.",
        underlying_controller="PcController",
        underlying_capability_name="pc_media_play_pause",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_MEDIA_NEXT",
        subsystem=Subsystem.PC,
        description="Sends VK_MEDIA_NEXT_TRACK virtual keybd_event to active Windows media application.",
        underlying_controller="PcController",
        underlying_capability_name="pc_media_next",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_MEDIA_PREVIOUS",
        subsystem=Subsystem.PC,
        description="Sends VK_MEDIA_PREV_TRACK virtual keybd_event to active Windows media application.",
        underlying_controller="PcController",
        underlying_capability_name="pc_media_previous",
        operation_type=OperationType.ACTION,
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_MEDIA_STOP",
        subsystem=Subsystem.PC,
        description="Sends VK_MEDIA_STOP virtual keybd_event to active Windows media application.",
        underlying_controller="PcController",
        underlying_capability_name="pc_media_stop",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_GET_POWER_STATE",
        subsystem=Subsystem.PC,
        description="Reads Windows power state, AC mains status, battery percentage, uptime, and OS build info.",
        underlying_controller="PcController",
        underlying_capability_name="pc_get_power_state",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_LOCK",
        subsystem=Subsystem.PC,
        description="Locks the Windows workstation via user32.LockWorkStation.",
        underlying_controller="PcController",
        underlying_capability_name="pc_lock",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_SLEEP",
        subsystem=Subsystem.PC,
        description="Puts the Windows host PC into standby sleep via SetSuspendState.",
        underlying_controller="PcController",
        underlying_capability_name="pc_sleep",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.MEDIUM_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="PC_LAUNCH_ALLOWLISTED_APP",
        subsystem=Subsystem.PC,
        description="Launches an allowlisted safe desktop application (spotify, chrome, notepad, calculator, vlc, taskmgr, explorer).",
        underlying_controller="PcController",
        underlying_capability_name="pc_launch_allowlisted_app",
        operation_type=OperationType.ACTION,
        parameters={
            "app_key": ParameterConstraint(
                name="app_key",
                param_type=ParameterType.ENUM,
                required=True,
                allowed_values=["spotify", "chrome", "notepad", "calculator", "vlc", "taskmgr", "explorer"],
                description="Allowlisted application key"
            )
        },
        idempotent=False,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),

    # =========================================================================
    # 5. SOUNDBAR / AUDIO ROUTING SUBSYSTEM (LG SNC4R / SmartRoomOrchestrator)
    # =========================================================================
    CapabilityDefinition(
        canonical_id="SOUNDBAR_ROUTE_TO_FIRE_TV",
        subsystem=Subsystem.SOUNDBAR,
        description="Transfers LG SNC4R Soundbar Bluetooth audio connection from PC to Fire TV.",
        underlying_controller="SmartRoomOrchestrator",
        underlying_capability_name="soundbar_route_to_fire_tv",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"soundbar.current_owner": "FIRE_TV", "soundbar.is_connected": True}
    ),
    CapabilityDefinition(
        canonical_id="SOUNDBAR_ROUTE_TO_PC",
        subsystem=Subsystem.SOUNDBAR,
        description="Restores LG SNC4R Soundbar Bluetooth audio connection from Fire TV back to PC.",
        underlying_controller="SmartRoomOrchestrator",
        underlying_capability_name="soundbar_route_to_pc",
        operation_type=OperationType.ACTION,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE,
        expected_state_transition={"soundbar.current_owner": "PC", "soundbar.is_connected": True}
    ),
    CapabilityDefinition(
        canonical_id="SOUNDBAR_GET_OWNERSHIP",
        subsystem=Subsystem.SOUNDBAR,
        description="Reads current active audio owner and connection state for LG SNC4R Soundbar.",
        underlying_controller="SmartRoomOrchestrator",
        underlying_capability_name="soundbar_get_ownership",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),

    # =========================================================================
    # 6. LIGHTING SUBSYSTEM (Tuya / Smart Life Wi-Fi / LightController)
    # =========================================================================
    CapabilityDefinition(
        canonical_id="LIGHT_GET_STATUS",
        subsystem=Subsystem.LIGHTING,
        description="Reads live smart lighting status (power, brightness, color temperature, active scene).",
        underlying_controller="LightController",
        underlying_capability_name="get_status",
        operation_type=OperationType.QUERY,
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=False,
        safety_level=SafetyLevel.SAFE,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="LIGHT_SET_POWER",
        subsystem=Subsystem.LIGHTING,
        description="Turns smart lighting power ON or OFF.",
        underlying_controller="LightController",
        underlying_capability_name="set_power",
        operation_type=OperationType.ACTION,
        parameters={
            "power": ParameterConstraint(
                name="power",
                param_type=ParameterType.BOOLEAN,
                required=True,
                description="Power state (True for ON, False for OFF)"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="LIGHT_SET_BRIGHTNESS",
        subsystem=Subsystem.LIGHTING,
        description="Adjusts smart lighting brightness between 1 and 100%.",
        underlying_controller="LightController",
        underlying_capability_name="set_brightness",
        operation_type=OperationType.ACTION,
        parameters={
            "brightness": ParameterConstraint(
                name="brightness",
                param_type=ParameterType.INTEGER,
                required=True,
                min_value=1,
                max_value=100,
                description="Brightness percentage (1 to 100)"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="LIGHT_SET_COLOR_TEMP",
        subsystem=Subsystem.LIGHTING,
        description="Sets smart lighting color temperature in Kelvin (2200K to 6500K).",
        underlying_controller="LightController",
        underlying_capability_name="set_color_temp",
        operation_type=OperationType.ACTION,
        parameters={
            "kelvin": ParameterConstraint(
                name="kelvin",
                param_type=ParameterType.INTEGER,
                required=True,
                min_value=2200,
                max_value=6500,
                description="Color temperature in Kelvin (2200 to 6500)"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    ),
    CapabilityDefinition(
        canonical_id="LIGHT_SET_SCENE",
        subsystem=Subsystem.LIGHTING,
        description="Applies a predefined lighting preset scene (RELAX, FOCUS, NIGHT, CINEMA, DAY, OFF).",
        underlying_controller="LightController",
        underlying_capability_name="set_scene",
        operation_type=OperationType.ACTION,
        parameters={
            "scene_name": ParameterConstraint(
                name="scene_name",
                param_type=ParameterType.ENUM,
                required=True,
                allowed_values=["RELAX", "FOCUS", "NIGHT", "CINEMA", "DAY", "OFF"],
                description="Preset lighting scene"
            )
        },
        idempotent=True,
        requires_device_online=True,
        readback_verification_expected=True,
        safety_level=SafetyLevel.LOW_RISK,
        status=CapabilityStatus.VERIFIED_EXECUTABLE
    )
]
